version: '3.7'

services:
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    command: gunicorn -w 4 --bind 0.0.0.0:5000 portal:app
    # command: gunicorn -w 4 -b 127.0.0.1:4000 demoportal:app 
    #volumes:
    #  - ./agw/static:/app/portal/static
    #  - ./agw/media:/app/portal/media
        # - media_volume:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env.portal
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
        # - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  agw:
    container_name: agw
    hostname: agw
    image: nginx
    ports:
      - 11080:80
      - 11443:443
    volumes:
      # - ./nginx/sites-available/default:/etc/nginx/sites-available/default
      - ./agw/conf.d:/etc/nginx/conf.d
      - ./agw/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./agw/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./agw/static:/app/web/portal/static
      - ./agw/media:/app/web/portal/media
      # - media_volume:/app/web/project/media
    networks:
      - default
    depends_on:
      - portal 

        #  nginx:
        #    build: ./nginx
        #    volumes:
        #    ports:
        #      - 1337:80

        # volumes:
        #  postgres_data:
        #  static_volume:
        #  media_volume:
