"""empty message

Revision ID: 0941bdf8b43c
Revises: 29daf0a927c8
Create Date: 2019-03-28 17:52:25.869653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0941bdf8b43c'
down_revision = '29daf0a927c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apis', sa.Column('desc_text', sa.String(length=128), nullable=True))
    op.add_column('apis', sa.Column('display_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apis', 'display_name')
    op.drop_column('apis', 'desc_text')
    # ### end Alembic commands ###
