"""empty message

Revision ID: 150c955eda6c
Revises: 9d92a85fa0b5
Create Date: 2019-05-13 10:31:44.604222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150c955eda6c'
down_revision = '9d92a85fa0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_port_map', sa.Column('container_port', sa.Integer(), nullable=True))
    op.add_column('container_port_map', sa.Column('proxy_port', sa.Integer(), nullable=True))
    op.drop_column('container_port_map', 'port')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_port_map', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('container_port_map', 'proxy_port')
    op.drop_column('container_port_map', 'container_port')
    # ### end Alembic commands ###
