"""empty message

Revision ID: 34b247c572fb
Revises: 7311796fb157
Create Date: 2019-05-03 14:52:25.786091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b247c572fb'
down_revision = '7311796fb157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_queue_client_id', sa.Integer(), nullable=True),
    sa.Column('cmd', sa.JSON(), nullable=True),
    sa.Column('ts_created', sa.DateTime(), nullable=True),
    sa.Column('ts_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_queue_client_id'], ['task_queue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_queue_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('ips', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('lxd', 'docker', name='containertypes'), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('ts_created', sa.DateTime(), nullable=True),
    sa.Column('ts_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_license_id'), 'container', ['license_id'], unique=False)
    op.create_table('key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('ed25519', 'rsa', name='keytypes'), nullable=True),
    sa.Column('private_key', sa.String(length=256), nullable=True),
    sa.Column('public_key', sa.String(length=256), nullable=True),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orgs', sa.Column('note', sa.String(length=256), nullable=True))
    op.drop_column('orgs', 'notes')
    op.add_column('products', sa.Column('note', sa.String(length=256), nullable=True))
    op.drop_column('products', 'notes')
    op.add_column('users', sa.Column('note', sa.String(length=256), nullable=True))
    op.drop_column('users', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notes', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('users', 'note')
    op.add_column('products', sa.Column('notes', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('products', 'note')
    op.add_column('orgs', sa.Column('notes', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('orgs', 'note')
    op.drop_table('key')
    op.drop_index(op.f('ix_container_license_id'), table_name='container')
    op.drop_table('container')
    op.drop_table('task_queue_client')
    op.drop_table('task_queue')
    # ### end Alembic commands ###
