"""empty message

Revision ID: 353ebf10b11c
Revises: 0178143f0610
Create Date: 2019-05-07 13:03:41.428060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353ebf10b11c'
down_revision = '0178143f0610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_queue', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_queue', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_queue', type_='foreignkey')
    op.drop_column('task_queue', 'user_id')
    # ### end Alembic commands ###
