"""empty message

Revision ID: 393219824c73
Revises: 159cb52d53a2
Create Date: 2019-05-06 20:04:35.586514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393219824c73'
down_revision = '159cb52d53a2'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # keyciphers = postgresql.ENUM('active', 'inactive', 'archive', name='keyciphers')
    # banner_status.create(op.get_bind())
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('key', sa.Column('key_cipher', sa.Enum('ed25519', 'rsa', name='keyciphers'), nullable=True))
    # op.add_column('key', sa.Column('key_format', sa.Enum('openssh', 'pem', 'pkcs12', name='keyformats'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('key', 'key_format')
    # op.drop_column('key', 'key_cipher')
    # ### end Alembic commands ###
