"""empty message

Revision ID: 70eb47c5be4f
Revises: 4c3eea649e45
Create Date: 2019-05-06 18:56:51.652508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70eb47c5be4f'
down_revision = '4c3eea649e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('add_to_authorized_keys', sa.Boolean(), nullable=True))
    op.add_column('key', sa.Column('key_cipher', sa.Enum('ed25519', 'rsa', name='keytypes'), nullable=True))
    op.add_column('key', sa.Column('key_format', sa.Enum('ed25519', 'rsa', name='keytypes'), nullable=True))
    op.drop_column('key', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('type', postgresql.ENUM('ed25519', 'rsa', name='keytypes'), autoincrement=False, nullable=True))
    op.drop_column('key', 'key_format')
    op.drop_column('key', 'key_cipher')
    op.drop_column('key', 'add_to_authorized_keys')
    # ### end Alembic commands ###
