"""empty message

Revision ID: 7311796fb157
Revises: 230cc02c69a7
Create Date: 2019-04-12 14:31:41.213548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7311796fb157'
down_revision = '230cc02c69a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_to_sms', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('otp_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_has_sms', sa.Boolean(), nullable=True))
    op.drop_column('users', 'sms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sms', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone_has_sms')
    op.drop_column('users', 'otp_enabled')
    op.drop_column('users', 'email_to_sms')
    # ### end Alembic commands ###
