"""empty message

Revision ID: a4fe05917039
Revises: 393219824c73
Create Date: 2019-05-06 20:13:01.825084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a4fe05917039'
down_revision = '393219824c73'
branch_labels = None
depends_on = None


def upgrade():
    keycipher = postgresql.ENUM('ed25519', 'rsa', 'keycipher', name='keycipher')
    keycipher.create(op.get_bind())
    keyformat = postgresql.ENUM('openssh', 'pem', 'pkcs12', name='keyformat')
    keyformat.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('key_cipher', sa.Enum('ed25519', 'rsa', name='keycipher'), nullable=True))
    op.add_column('key', sa.Column('key_format', sa.Enum('openssh', 'pem', 'pkcs12', name='keyformat'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key', 'key_format')
    op.drop_column('key', 'key_cipher')
    # ### end Alembic commands ###
