"""empty message

Revision ID: bb7a2d75394d
Revises: 9f39b0404f06
Create Date: 2019-05-09 16:52:14.417958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7a2d75394d'
down_revision = '9f39b0404f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_queue_task_queue_client_id_fkey', 'task_queue', type_='foreignkey')
    op.create_foreign_key(None, 'task_queue', 'task_queue_client', ['task_queue_client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_queue', type_='foreignkey')
    op.create_foreign_key('task_queue_task_queue_client_id_fkey', 'task_queue', 'task_queue', ['task_queue_client_id'], ['id'])
    # ### end Alembic commands ###
