"""empty message

Revision ID: c0410ac87519
Revises: 0941bdf8b43c
Create Date: 2019-03-28 18:32:31.511245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0410ac87519'
down_revision = '0941bdf8b43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'apis', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apis', type_='unique')
    # ### end Alembic commands ###
