"""empty message

Revision ID: d4849e54eec3
Revises: 84d75343fc9d
Create Date: 2019-05-06 20:44:33.409328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4849e54eec3'
down_revision = '84d75343fc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('private_key', sa.String(length=1024), nullable=True))
    op.add_column('key', sa.Column('public_key', sa.String(length=512), nullable=True))
    op.drop_column('key', 'private_keys')
    op.drop_column('key', 'public_keys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('public_keys', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('key', sa.Column('private_keys', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('key', 'public_key')
    op.drop_column('key', 'private_key')
    # ### end Alembic commands ###
