"""empty message

Revision ID: dc0d6d864c1e
Revises: cd27a94f723f
Create Date: 2019-03-28 14:36:53.115026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0d6d864c1e'
down_revision = 'cd27a94f723f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('note', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_tokens', 'note')
    # ### end Alembic commands ###
