"""empty message

Revision ID: f196fd3be622
Revises: 353ebf10b11c
Create Date: 2019-05-09 12:04:29.696617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f196fd3be622'
down_revision = '353ebf10b11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_queue', 'ts_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('task_queue', 'ts_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_queue', 'ts_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task_queue', 'ts_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
