"""empty message

Revision ID: 1ae5f99f213c
Revises: 70eb47c5be4f
Create Date: 2019-05-06 19:30:20.804321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ae5f99f213c'
down_revision = '70eb47c5be4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key', 'key_format')
    op.drop_column('key', 'key_cipher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('key_cipher', postgresql.ENUM('ed25519', 'rsa', name='keytypes'), autoincrement=False, nullable=True))
    op.add_column('key', sa.Column('key_format', postgresql.ENUM('ed25519', 'rsa', name='keytypes'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
