"""empty message

Revision ID: 31fe8b0f3a0d
Revises: f196fd3be622
Create Date: 2019-05-09 12:15:04.146609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31fe8b0f3a0d'
down_revision = 'f196fd3be622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_queue', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('task_queue', 'ts_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task_queue', 'ts_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_queue', 'ts_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('task_queue', 'ts_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('task_queue', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
