"""empty message

Revision ID: 595333e172df
Revises: 34b247c572fb
Create Date: 2019-05-06 14:22:32.899160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595333e172df'
down_revision = '34b247c572fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssh_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('private', sa.String(length=128), nullable=True),
    sa.Column('public', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('container', sa.Column('ssh_key_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'container', 'ssh_key', ['ssh_key_id'], ['id'])
    op.add_column('task_queue', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_queue', 'completed')
    op.drop_constraint(None, 'container', type_='foreignkey')
    op.drop_column('container', 'ssh_key_id')
    op.drop_table('ssh_key')
    # ### end Alembic commands ###
