"""empty message

Revision ID: 7e3605c36946
Revises: bb7a2d75394d
Create Date: 2019-05-09 18:08:54.701174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3605c36946'
down_revision = 'bb7a2d75394d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('container', sa.Column('deleted', sa.DateTime(), nullable=True))
    op.add_column('container', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('container', 'status')
    op.drop_column('container', 'deleted')
    op.drop_column('container', 'created')
    # ### end Alembic commands ###
