"""empty message

Revision ID: 943eac548d49
Revises: 4d075534c323
Create Date: 2019-03-19 12:12:08.058853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943eac548d49'
down_revision = '4d075534c323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_ts', sa.DateTime(), nullable=True))
    op.drop_column('users', 'reset_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'reset_token_ts')
    # ### end Alembic commands ###
