"""empty message

Revision ID: 9f39b0404f06
Revises: 31fe8b0f3a0d
Create Date: 2019-05-09 12:25:19.389310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '9f39b0404f06'
down_revision = '31fe8b0f3a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_queue', 'ts_created',
               existing_type=postgresql.TIMESTAMP(),
               server_default=False,
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
