"""empty message

Revision ID: ab2f1cdac54c
Revises: 150c955eda6c
Create Date: 2019-05-13 12:27:13.061402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2f1cdac54c'
down_revision = '150c955eda6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container_port_map', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('container_port_map', sa.Column('deleted', sa.DateTime(), nullable=True))
    op.add_column('container_port_map', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('container_port_map', 'status')
    op.drop_column('container_port_map', 'deleted')
    op.drop_column('container_port_map', 'created')
    # ### end Alembic commands ###
