"""empty message

Revision ID: cb637b0660a9
Revises: 1ae5f99f213c
Create Date: 2019-05-06 19:34:18.078637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb637b0660a9'
down_revision = '1ae5f99f213c'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
